{% set name = "esgf-pyclient" %}
{% set version = "0.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 616ad5e1b0d04733779a88db3ddf5984ea287e70f3d7ad096c3a26664b693381

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip
  run:
    - python >=3.6
    - jinja2
    - requests
    - requests_cache
    - webob
    - defusedxml
    - myproxyclient

test:
  imports:
    - pyesgf
    - pyesgf.search
    - pyesgf.security

about:
  home: http://esgf-pyclient.readthedocs.org
  license: BSD-3-Clause
  license_file: LICENSE
  summary: A library interacting with ESGF services within Python

extra:
  recipe-maintainers:
    - agoodm
    - jarifibrahim
    - agstephens
    - cehbrecht
    - bouweandela
