{% set name = "esgf-pyclient" %}
{% set version = "0.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 35778bd411c976192bc581e41d7c80e5151dabc60277c35f2700c9af13dd63c2

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python
    - pip
  run:
    - python
    - jinja2
    - requests
    - requests_cache
    - six

test:
  imports:
    - pyesgf
    - pyesgf.search
    - pyesgf.security

about:
  home: http://esgf-pyclient.readthedocs.org
  license: BSD 3-clause
  license_file: LICENSE
  summary: 'A library interacting with ESGF services within Python'

extra:
  recipe-maintainers:
    - agoodm
    - jarifibrahim
    - agstephens
    - cehbrecht
