{% set name = "esgf-pyclient" %}
{% set version = "0.1.8" %}
{% set hash_type = "md5" %}
{% set hash_val = "754d7e1e3128ef4d5ac481e4bb751ef7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  {{ hash_type }}: {{ hash_val }}

build:
  skip: True  # [py3k]
  number: 1001
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - jinja2

test:
  imports:
    - pyesgf
    - pyesgf.search
    - pyesgf.security

about:
  home: http://esgf-pyclient.readthedocs.org
  license: BSD 3-clause
  license_file: LICENSE
  summary: 'A library interacting with ESGF services within Python'

extra:
  recipe-maintainers:
    - agoodm
    - jarifibrahim
    - agstephens
