appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: FUHqHlE+7vTB5y1esm96DGCL/s+g2fnpVvFxJ6aTKDGj6OoYYBkMwUbKm1I47Yo3IZHNmrDv0pbYNLBIsBTBS2e3lZDCUuSOYGFFoFBD1ZAbCtixl4pAmUyz1Bfl1Y6LCcQWZqcv3fCKzErp+NXBD/4GsyP85mbTVlmMIaNknSsiG1meXWMBeeuy7/qwVBBHWelV5GmIvRaJK4WeD7LLUg0jPcWnomyrJzrpaor515L1I/lt+YRpj/Sw6hsgPJJMIH9LK8ltEWhllcYZTsE0/vu1oPjS7+sdxkfRJYaXt938Ch+APyNzaOtHDOtypOs/OAmxhTLSt6lOyma9XVsfdXSAmqBo0BfzFdFj4nNsuZi3q+CZM6pyiT07Vxxv4MN0nQZy/796LqVjeC6q2o8dVmCgTHFvZaS/PVJC3NMTL6h+Q3OpWJDYypks4MWJmzt/FBFBnnSTNEdZQRAQRQmv9h78BfYZpfsTKK8Lci98FoRiFrEfVA9D8wdfjoTPBXcmPvM36P+ITcACsrmAUvsKQe055wlc4M8Qr4k5W3pEXzjVq+bU+YTM/exYFA8TLbxEqSaOECLOWBI+Rev86tH5VCkb5eJMZGEg1oDt6Tng7XUHQAY/niLqVmInB3hElugNzn+z7TvqnlB+1rRPTgKH9f168C7+LbhEskGSGWyYpyc=}
conda_forge_output_validation: true
